# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f056f57c44a1a0a99d3a16e5de566d3b5c7e311f4f79b02169de93ecf2905750808413980f1ed99a786a54f39c440b8a78666ba3822adea3a050f8e6d05e17c8

test:
  secret_key_base: beab4321611373a804e4d38ce19e4bd0763267bde20dbef4daadf136762890138dffc10c1afb16743332a07a64aaf16ce70a96afc5a72606dbeac3c5ac56f802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
